site_name: 'Weber Auto Electronics Lab'
site_description: 'Electronics Lab at Weber State University'
repo_url: 'https://github.com/scotthadzik/PiLabSite'
repo_name: 'GitHub'
docs_dir: 'docs/'
site_dir: '_site_mkdocs/'
theme: 'readthedocs'
prev_next_buttons_location: 'both'
copyright: 'Scott Hadzik'
