title: Vehicle Electronics - Computer Controlled Circuits
description: Computer controlled circuits
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Scott Hadzik
repo_url: "https://github.com/scotthadzik/PiLabSite"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
